spring.application.name=spring_security_demo
spring.security.user.name=hello
spring.security.user.password=hello@123

# database
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=test@123

#h2-console
spring.h2.console.enabled=true
